services:
  web:
    image: thekampany/trippanion_web:latest
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - static_volume:/usr/src/app/staticfiles
      - media_volume:/usr/src/app/media
    expose:
      - 8000
    env_file:
      - .env
    depends_on:
      - db
    container_name: trippanion_web

  nginx:
    image: thekampany/trippanion_nginx:latest
    build:
      context: .
      dockerfile: Dockerfile.nginx
    container_name: trippanion_nginx
    ports:
      - "8043:8043"
    volumes:
      - static_volume:/usr/src/app/staticfiles
      - media_volume:/usr/src/app/media
    depends_on:
      - web

  db:
    image: postgres:13
    container_name: trippanion_db
    volumes:
      - tripapp_postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: tripappdb
      POSTGRES_USER: tripappuser
      POSTGRES_PASSWORD: tripapppassword

volumes:
  static_volume:
  media_volume:
  tripapp_postgres_data:
