
version: '3.9'

services:
  web:
    build: .
    command: "uvicorn tripproject.asgi:application --host 0.0.0.0 --port 8043"
    volumes:
      - static_volume:/usr/src/app/staticfiles
      - media_volume:/usr/src/app/media
    expose:
      - 8043
    env_file:
      - .env
    depends_on:
      - db
    container_name: trippanion_web

  nginx:
    image: nginx:latest
    container_name: trippanion_nginx
    ports:
      - "8043:8043"
    volumes:
      - static_volume:/usr/src/app/staticfiles
      - media_volume:/usr/src/app/media
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - web

  db:
    image: postgres:13
    container_name: trippanion_db
    volumes:
      - tripapp_postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: tripappdb
      POSTGRES_USER: tripappuser
      POSTGRES_PASSWORD: tripapppassword


volumes:
  static_volume:
  media_volume:
  tripapp_postgres_data:
