from django.urls import path, include
from . import views
from django.contrib.auth.views import LoginView,LogoutView
from django.contrib import admin
from django.contrib.auth import views as auth_views
from rest_framework.routers import DefaultRouter

app_name = 'tripapp'

router = DefaultRouter()
router.register(r'trips', views.TripViewSet)
router.register(r'logentries', views.LogEntryViewSet)


urlpatterns = [
    path('api/', include(router.urls)),
    path('api/tribes/<uuid:tribe_id>/trips/', views.TripsByTribeView.as_view(), name='trips-by-tribe'),
    path('api/tribes/<uuid:tribe_id>/map-data/', views.TribeMapDataAPIView.as_view(), name='tribe-map-data'),
    path('api/trippers/<int:tripper_id>/trips/', views.TripsByTripperView.as_view(), name='trips-by-tripper'),
    path("api/tripoutlines/", views.TripOutlineCreateView.as_view(), name="tripoutline-create"),
    path('api/import_itinerary/', views.import_itineraryidea, name='import_itineraryidea'),
    path('index', views.index, name='index'),
    path('', views.index, name='index'),
    path('home', views.trip_list, name='trip_list'),
    path('<uuid:tribe_id>/trip/create/', views.create_trip, name='create_trip'),
    path('<uuid:tribe_id>/map/', views.tribe_map_view, name='tribe_map_view'),
    path('trip/<slug:slug>/', views.trip_detail, name='trip_detail'),
    path('trip/<int:trip_id>/trippers/', views.trip_trippers, name='trip_trippers'),
    path('trip/<int:trip_id>/tripper_list/', views.tripper_list, name='tripper_list'),
    path('trip/<int:trip_id>/tripper/<int:tripper_id>/badgeassignments/', views.trip_tripper_badgeassignments, name='trip_tripper_badgeassignments'),
    path('trip/<int:trip_id>/update/', views.trip_update, name='trip_update'),
    path('trip/<int:trip_id>/add_checklist_item/', views.add_checklist_item, name='add_checklist_item'),
    path('trip/<int:trip_id>/map/', views.trip_map_view, name='trip_map_view'),
    path('trip/<int:trip_id>/tripperbingocard/', views.trip_tripper_bingocard, name='trip_tripper_bingocard'),
    path('trip/<int:trip_id>/bingocards/', views.trip_bingocards, name='trip_bingocards'),
    path('trip/<int:trip_id>/bingocardsadmin/', views.tripadmin_bingocards, name='tripadmin_bingocards'),
    path('trip/<int:trip_id>/bingocards/add/', views.add_bingocard, name='add_bingocard'),
    path('trip/<int:trip_id>/dayprogram/<int:dayprogram_id>/points/', views.trip_dayprogram_points, name='trip_dayprogram_points'),
    path('trip/<int:trip_id>/dayprograms/', views.trip_dayprograms, name='trip_dayprograms'),
    path('trip/<int:trip_id>/add_trippers/<uuid:tribe_id>/', views.add_trippers, name='add_trippers'),
    path('trip/<int:trip_id>/points/', views.trip_points, name='trip_points'),
    path('trip/<int:trip_id>/points/add/', views.add_point, name='add_point'),
    path('trip/<int:trip_id>/point/<int:point_id>/edit/', views.edit_point, name='edit_point'),
    path('trip/<int:trip_id>/point/<int:point_id>/delete/', views.delete_point, name='delete_point'),
    path('trip/<int:trip_id>/dayprogram/add/', views.dayprogram_add, name='dayprogram_add'),
    path('trip/<int:trip_id>/upload_route/', views.upload_route, name='upload_route'),
    path('trip/<int:trip_id>/route/<int:route_id>/delete/', views.delete_route, name='delete_route'),
    path('trip/<int:trip_id>/tripper/<int:tripper_id>/add_expense/', views.add_expense, name='add_expense'),
    path('trip/<int:trip_id>/balance/', views.trip_balance, name='trip_balance'),
    path('trip/<int:trip_id>/expenses/', views.trip_expenses_list, name='trip_expenses_list'),
    path('trip/<int:trip_id>/budget/add/', views.budget_add, name='budget_add'),
    path('trip/<int:trip_id>/budget/list/', views.budget_list, name='budget_list'),
    path('trip/<int:trip_id>/budget/<int:budget_id>/edit/', views.budget_update, name='budget_update'),
    path('trip/<int:trip_id>/budget-analysis/', views.trip_budget_analysis, name='trip_budget_analysis'),
    path('trip/<int:trip_id>/reorder_dayprograms/', views.reorder_dayprograms, name='reorder_dayprograms'),
    path('trip/<int:trip_id>/export/', views.export_trip, name="export_trip"),
    path('trip/<int:trip_id>/archive/', views.create_zip_with_html, name="export_trip_html_zip"),
    path('trip/<int:trip_id>/export/tripoutline/', views.create_trip_outline_html, name="create_trip_outline_html"),
    path('trip/<int:trip_id>/export/tripoutline-json/', views.export_trip_outline_json, name='export_trip_outline_json'),
    path('trip/<slug:slug>/checklist/', views.trip_checklist, name='trip_checklist'),
    path('tripper/<int:tripper_id>/profile/', views.tripper_profile, name='tripper_profile'),
    path('tripper/<int:tripper_id>/badgeassignments/', views.tripper_badgeassignments, name='tripper_badgeassignments'),
    path('tripper/<int:tripper_id>/trip/<int:trip_id>/edit/', views.edit_tripper, name='edit_tripper'),
    path('dayprogram/<int:dayprogram_id>/', views.dayprogram_detail, name='dayprogram_detail'),
    path('dayprogram/<int:dayprogram_id>/add_image/', views.add_image, name='add_image'),
    path('dayprogram/<int:dayprogram_id>/check_answer/<int:questionid>/', views.check_answer, name='check_answer'),
    path('dayprogram/<int:dayprogram_id>/edit/', views.edit_dayprogram, name='edit_dayprogram'),
    path('dayprogram/<int:dayprogram_id>/questions', views.dayprogram_questions, name='dayprogram_questions'),
    path('dayprogram/<int:dayprogram_id>/questions/add/', views.add_question, name='add_question'),
    path('dayprogram/<int:dayprogram_id>/add_logentry/', views.add_logentry, name='add_logentry'),
    path('dayprogram/<int:dayprogram_id>/add-badge-and-question/', views.add_badge_and_question, name='add_badge_and_question'),
    path('dayprogram/<int:dayprogram_id>/links', views.dayprogram_links, name='dayprogram_links'),
    path('dayprogram/<int:dayprogram_id>/add-link/', views.add_link, name='add_link'),
    path('dayprogram/<int:dayprogram_id>/edit-link/<int:link_id>/', views.edit_link, name='edit_link'),
    path('dayprogram/<int:dayprogram_id>/delete-link/<int:link_id>/', views.delete_link, name='delete_link'),
    path('dayprogram/<int:dayprogram_id>/add_suggestion/', views.add_suggestion, name='add_suggestion'),
    path('dayprogram/<int:dayprogram_id>/scheduled-items', views.dayprogram_scheduled_items, name='dayprogram_scheduled_items'),
    path('dayprogram/<int:dayprogram_id>/scheduled-item/add/', views.add_or_edit_scheduled_item, name='add_scheduled_item'),
    path('dayprogram/<int:dayprogram_id>/scheduled-item/<int:scheduled_item_id>/edit/', views.add_or_edit_scheduled_item, name='edit_scheduled_item'),
    path('dayprogram/<int:dayprogram_id>/scheduled-item/<int:scheduled_item_id>/delete/', views.delete_scheduled_item, name='delete_scheduled_item'),
    path('question/<int:question_id>/edit/', views.edit_question, name='edit_question'),
    path('badges/', views.badge_list, name='badge_list'),
    path('mytribesbadges/', views.mytribes_badges_view, name='mytribes_badges_view'),
    path('badge_claimed/<int:badge_id>/', views.badge_claimed, name='badge_claimed'),
    path('upload_badge/', views.upload_badge, name='upload_badge'),
    path("badge/create/", views.badge_creator, name="badge_creator"),
    path("badge/save/", views.save_badge, name="save_badge"),
    path('checklist_item/<int:item_id>/toggle/', views.toggle_checklist_item, name='toggle_checklist_item'),
    path('toggle_checklist_item/<int:item_id>/', views.toggle_checklist_item, name='toggle_checklist_item'),
    path('accounts/login/', LoginView.as_view(), name='login'),
    path('accounts/logout/', LogoutView.as_view(), name='logout'),
    path('register/', views.register, name='register'),
    path('bingocard/<int:pk>/', views.bingocard_detail, name='bingocard_detail'),
    path('bingocard/<int:bingocard_id>/upload/', views.upload_answerimage, name='upload_answerimage'),
    #path('tribe/<uuid:tribe_id>/trips/', views.tribe_trips, name='tribe_trips'),
    path('organize', views.tribe_trips, name='tribe_trips'),
    path('organize/<uuid:tribe_id>/trip/<int:trip_id>/', views.tribe_trip_organize, name='tribe_trip_organize'),
    path('invite/', views.invite_to_tribe, name='invite_to_tribe'),
    path('register/invite/<uid>/', views.register_invite, name='register_invite'),
    path('tribe/create/', views.create_tribe, name='create_tribe'),
    path('permission_denied/', views.permission_denied, name='permission_denied'),
    path('password_reset/', auth_views.PasswordResetView.as_view(), name='password_reset'),
    path('password_reset/done/', auth_views.PasswordResetDoneView.as_view(), name='password_reset_done'),
    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('reset/done/', auth_views.PasswordResetCompleteView.as_view(), name='password_reset_complete'),
    path('save_event/', views.save_event, name='save_event'),
    path('set_timezone/', views.set_timezone, name='set_timezone'),
    path('profile/update/', views.update_profile, name='update_profile'),
    path("tasks/", views.task_manager, name="task_manager"),
    path('documents/<int:trip_id>/', views.trip_documents_view, name='trip_documents'),
    path('upload_document/', views.upload_tripper_document, name='upload_tripper_document'),
    path('delete_document/<int:document_id>/', views.delete_tripper_document, name='delete_tripper_document'),
    path('tripoutline/save/', views.save_tripoutline, name='save_tripoutline'),
    path('tripoutline/save/daylocations/', views.save_tripoutline_daylocations, name='save_tripoutline_daylocations'),
    path('itineraryidea/', views.pastecreate_itineraryidea, name='pastecreate_itineraryidea'),
    path('itineraryidea/daylocations/', views.create_itineraryidea_daylocations, name='create_itineraryidea_daylocations'),
    path('itineraryidea/overnightlocations/', views.create_itineraryidea_overnightlocations, name='create_itineraryidea_overnightlocations'),
    path('itineraryidea/<int:pk>/cluster/', views.itinerary_daylocations_dragdrop, name='itinerary_daylocations_dragdrop'),
    path('itineraryidea/daylocationassignments/', views.save_daylocation_assignments, name='save_daylocation_assignments'),
    path('itinerary/schema/', views.itinerary_schema_view, name='itinerary-schema'),
    path('itineraryideas/', views.itineraryidea_list, name='itineraryidea-list'),
    path('itineraryidea/<int:pk>/delete/', views.itineraryidea_delete, name="itineraryidea-delete"),
    path('itineraryidea/<int:pk>/edit/', views.itineraryidea_edit, name="itineraryidea-edit"),
    path('itineraryidea/<int:pk>/update/', views.update_itineraryidea, name='update_itineraryidea'),
    path("itineraryidea/<int:pk>/to_trip/", views.itineraryidea_to_trip, name="itineraryidea-to-trip"),
 ]
