# Generated by Django 4.2.13 on 2024-05-28 20:11

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tripapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dayprogram',
            name='dayprogramnumber',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dayprogram',
            name='necessary_info',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='dayprogram',
            name='possible_activities',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='dayprogram',
            name='tripdate',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='date'),
            preserve_default=False,
        ),
    ]
