# Generated by Django 4.2.13 on 2024-05-31 18:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tripapp', '0004_checklist_checklistitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='day_program_images/')),
                ('description', models.CharField(blank=True, max_length=255)),
                ('day_program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='tripapp.dayprogram')),
            ],
        ),
    ]
