# Generated by Django 4.2.13 on 2024-06-01 19:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tripapp', '0005_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.CharField(max_length=255)),
                ('correct_answer', models.CharField(max_length=255)),
                ('badge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tripapp.badge')),
                ('dayprogram', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tripapp.dayprogram')),
            ],
        ),
    ]
