# Generated by Django 4.2.13 on 2024-06-02 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tripapp', '0006_question'),
    ]

    operations = [
        migrations.AddField(
            model_name='badge',
            name='achievement_method',
            field=models.CharField(choices=[('admin_assigned', 'Assigned by Admin'), ('question_correct', 'Correct Answer to Question')], default='admin_assigned', max_length=20),
        ),
    ]
