# Generated by Django 4.2.13 on 2024-06-02 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tripapp', '0007_badge_achievement_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
