# Generated by Django 4.2.13 on 2024-06-03 19:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tripapp', '0009_point'),
    ]

    operations = [
        migrations.AddField(
            model_name='point',
            name='trip',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='points', to='tripapp.trip'),
            preserve_default=False,
        ),
    ]
