# Generated by Django 4.2.13 on 2024-06-04 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tripapp', '0010_point_trip'),
    ]

    operations = [
        migrations.AddField(
            model_name='badge',
            name='assignment_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='badge',
            name='achievement_method',
            field=models.CharField(choices=[('admin_assigned', 'Assigned by Admin'), ('question_correct', 'Correct Answer to Question'), ('time_based', 'Assigned on a specific date')], default='admin_assigned', max_length=20),
        ),
    ]
