# Generated by Django 4.2.13 on 2024-06-05 17:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tripapp', '0011_badge_assignment_date_alter_badge_achievement_method'),
    ]

    operations = [
        migrations.CreateModel(
            name='BingoCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('bingoimage', models.ImageField(blank=True, null=True, upload_to='bingocards/')),
                ('answerimage', models.ImageField(blank=True, null=True, upload_to='answers/')),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bingocards', to='tripapp.trip')),
            ],
        ),
    ]
