# Generated by Django 4.2.13 on 2024-06-05 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tripapp', '0012_bingocard'),
    ]

    operations = [
        migrations.AddField(
            model_name='point',
            name='dayprograms',
            field=models.ManyToManyField(blank=True, related_name='points', to='tripapp.dayprogram'),
        ),
    ]
