# Generated by Django 4.2.13 on 2024-06-06 16:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tripapp', '0013_point_dayprograms'),
    ]

    operations = [
        migrations.CreateModel(
            name='BingoAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answerimage', models.ImageField(upload_to='bingoanswers/')),
                ('bingocard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tripapp.bingocard')),
                ('tripper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tripapp.tripper')),
            ],
        ),
    ]
