# Generated by Django 4.2.13 on 2024-06-07 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tripapp', '0014_bingoanswer'),
    ]

    operations = [
        migrations.AddField(
            model_name='tripper',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='tripper_photos/'),
        ),
    ]
