# Generated by Django 4.2.13 on 2024-06-13 19:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tripapp', '0015_tripper_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='BadgeAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_assigned', models.DateField(auto_now_add=True)),
                ('badge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='badge_assignments', to='tripapp.badge')),
                ('trip', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='badge_assignments', to='tripapp.trip')),
                ('tripper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='badge_assignments', to='tripapp.tripper')),
            ],
        ),
    ]
