# Generated by Django 4.2.13 on 2024-06-15 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tripapp', '0016_badgeassignment'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='country_codes',
            field=models.CharField(blank=True, help_text='Comma-separated list of country codes', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='trip',
            name='date_from',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trip',
            name='date_to',
            field=models.DateField(blank=True, null=True),
        ),
    ]
