# Generated by Django 4.2.13 on 2024-06-18 20:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tripapp', '0019_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='tribe',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='trips', to='tripapp.tribe'),
            preserve_default=False,
        ),
    ]
