# Generated by Django 4.2.13 on 2024-06-22 09:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tripapp', '0020_trip_tribe'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='tribe',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='user',
        ),
        migrations.RemoveField(
            model_name='trip',
            name='tribe',
        ),
        migrations.DeleteModel(
            name='Tribe',
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
