# Generated by Django 4.2.13 on 2024-06-27 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tripapp', '0024_alter_trip_tribe'),
    ]

    operations = [
        migrations.AddField(
            model_name='badge',
            name='level',
            field=models.CharField(choices=[('global', 'Global'), ('tribal', 'Tribal')], default='tribal', max_length=20),
        ),
    ]
