# Generated by Django 4.2.13 on 2024-06-29 14:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tripapp', '0025_badge_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='badge',
            name='tribe',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='badges', to='tripapp.tribe'),
        ),
    ]
