# Generated by Django 4.2.14 on 2024-07-28 11:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tripapp', '0027_tripper_is_trip_admin'),
    ]

    operations = [
        migrations.CreateModel(
            name='LogEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logentry_text', models.TextField()),
                ('dayprogram', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logentries', to='tripapp.dayprogram')),
                ('tripper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logentries', to='tripapp.tripper')),
            ],
        ),
    ]
