# Generated by Django 4.2.14 on 2024-08-03 11:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tripapp', '0028_logentry'),
    ]

    operations = [
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(blank=True, null=True)),
                ('document', models.FileField(blank=True, null=True, upload_to='documents/')),
                ('dayprogram', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links', to='tripapp.dayprogram')),
            ],
        ),
    ]
