# Generated by Django 4.2.14 on 2024-08-03 12:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tripapp', '0029_link'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Link',
        ),
    ]
