# Generated by Django 4.2.14 on 2024-08-04 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tripapp', '0031_link'),
    ]

    operations = [
        migrations.RenameField(
            model_name='link',
            old_name='day_program',
            new_name='dayprogram',
        ),
        migrations.AddField(
            model_name='link',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
