# Generated by Django 4.2.14 on 2024-08-06 16:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tripapp', '0032_rename_day_program_link_dayprogram_link_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('gpx_file', models.FileField(upload_to='gpx_files/')),
                ('dayprogram', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='routes', to='tripapp.dayprogram')),
            ],
        ),
    ]
