# Generated by Django 4.2.14 on 2024-08-11 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tripapp', '0034_trip_use_facilmap'),
    ]

    operations = [
        migrations.AddField(
            model_name='point',
            name='marker_type',
            field=models.CharField(choices=[('default', 'Default'), ('bed', 'Bed')], default='default', max_length=20),
        ),
    ]
