# Generated by Django 4.2.14 on 2024-08-11 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tripapp', '0035_point_marker_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='badge',
            name='threshold_type',
            field=models.CharField(blank=True, choices=[('bingo_answer_uploads', 'Bingo Answer Uploads'), ('correct_answers', 'Correct Answers'), ('image_uploads', 'Image Uploads')], help_text='The type of threshold to achieve.', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='badge',
            name='threshold_value',
            field=models.PositiveIntegerField(blank=True, help_text='The value that needs to be reached to earn this badge.', null=True),
        ),
        migrations.AlterField(
            model_name='badge',
            name='achievement_method',
            field=models.CharField(choices=[('admin_assigned', 'Assigned by Admin'), ('question_correct', 'Correct Answer to Question'), ('time_based', 'Assigned on a specific date'), ('threshold', 'Assigned when number of uploads has been reached')], default='admin_assigned', max_length=20),
        ),
    ]
