# Generated by Django 4.2.24 on 2025-09-22 20:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tripapp', '0039_invitecode'),
    ]

    operations = [
        migrations.CreateModel(
            name='TripOutline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='badge',
            name='threshold_type',
            field=models.CharField(blank=True, choices=[('bingo_answer_uploads', 'Bingo Answer Uploads'), ('correct_answers', 'Correct Answers'), ('image_uploads', 'Image Uploads'), ('tripper_has_api_key', 'User has api integrations configured'), ('log_entries', 'Log Entries'), ('trip_count', 'Trip Count'), ('log_likes', 'Log Likes')], help_text='The type of threshold to achieve.', max_length=20, null=True),
        ),
        migrations.CreateModel(
            name='TripOutlineItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence', models.PositiveIntegerField()),
                ('description', models.TextField(blank=True, null=True)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('radius', models.PositiveIntegerField(default=0)),
                ('outline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='tripapp.tripoutline')),
            ],
            options={
                'ordering': ['sequence'],
            },
        ),
    ]
