# Generated by Django 4.2.24 on 2025-09-26 20:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tripapp', '0040_tripoutline_alter_badge_threshold_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tripoutline',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
