# Generated by Django 4.2.24 on 2025-09-26 20:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tripapp', '0041_tripoutline_created_by_tripoutline_updated_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tripoutlineitem',
            name='overnightlocation',
            field=models.TextField(blank=True, null=True),
        ),
    ]
