# Generated by Django 4.2.25 on 2025-10-01 19:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tripapp', '0043_tripoutline_created_by_tripoutline_updated_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItineraryIdea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itinerary_ideas', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ItineraryIdeaDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_sequence', models.PositiveIntegerField()),
                ('day_description', models.TextField(blank=True, null=True)),
                ('day_possible_date', models.DateField(blank=True, null=True)),
                ('itineraryidea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itineraryidea_days', to='tripapp.itineraryidea')),
            ],
            options={
                'ordering': ['day_sequence'],
            },
        ),
        migrations.CreateModel(
            name='OvernightLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('radius', models.PositiveIntegerField(default=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('day', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='overnightlocation', to='tripapp.itineraryideaday')),
            ],
        ),
        migrations.CreateModel(
            name='DayLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence', models.PositiveIntegerField()),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('radius', models.PositiveIntegerField(default=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='day_locations', to='tripapp.itineraryideaday')),
            ],
            options={
                'ordering': ['sequence'],
            },
        ),
    ]
