# Generated by Django 4.2.25 on 2025-10-01 20:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tripapp', '0044_itineraryidea_itineraryideaday_overnightlocation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='itineraryidea',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_itinerary_ideas', to=settings.AUTH_USER_MODEL),
        ),
    ]
