# Generated by Django 4.2.26 on 2025-12-07 13:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tripapp', '0045_itineraryidea_updated_by'),
    ]

    operations = [
        migrations.CreateModel(
            name='TripBudget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('category', models.CharField(blank=True, choices=[('', 'No Category'), ('Transportation', 'Transportation'), ('Lodging', 'Lodging'), ('Food and Drinks', 'Food and Drinks'), ('Activity', 'Activity'), ('Other', 'Other')], default='', max_length=20)),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='budget', to='tripapp.trip')),
            ],
        ),
    ]
