# Generated by Django 4.2.29 on 2026-04-04 19:36

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('tripapp', '0047_tripbudget_currency'),
    ]

    operations = [
        migrations.CreateModel(
            name='OllamaJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('model', models.CharField(default='mistral-small', max_length=100)),
                ('prompt', models.TextField()),
                ('answer', models.TextField(blank=True)),
                ('error', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('done', 'Done'), ('error', 'Error')], default='pending', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='scheduleditem',
            name='transportation_type',
            field=models.CharField(blank=True, choices=[('', 'Not Specified'), ('Airplane', 'Airplane'), ('Bus', 'Bus'), ('Train', 'Train'), ('Car', 'Car'), ('Taxi', 'Taxi'), ('Walking', ' Walking'), ('Cycling', 'Cycling'), ('Other', 'Other')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='tripbudget',
            name='currency',
            field=models.CharField(default='EUR', max_length=10),
            preserve_default=False,
        ),
    ]
