# Generated by Django 4.2.29 on 2026-04-04 19:36

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('tripapp', '0048_ollamajob_alter_scheduleditem_transportation_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scheduleditem',
            name='transportation_type',
            field=models.CharField(blank=True, choices=[('', 'Not Specified'), ('Airplane', 'Airplane'), ('Bus', 'Bus'), ('Train', 'Train'), ('Car', 'Car'), ('Taxi', 'Taxi'), ('Walking', 'Walking'), ('Cycling', 'Cycling'), ('Other', 'Other')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='tripbudget',
            name='currency',
            field=models.CharField(default='EUR', max_length=10),
            preserve_default=False,
        ),
    ]
