# Generated by Django 4.2.30 on 2026-04-21 20:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tripapp', '0049_alter_scheduleditem'),
    ]

    operations = [
        migrations.CreateModel(
            name='MapMarkerDraft',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.CharField(choices=[('pin', 'Activity / Visit'), ('bed', 'Overnight Location')], default='pin', max_length=20)),
                ('description', models.TextField(blank=True, null=True)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('sequence', models.PositiveIntegerField(default=0)),
                ('itinerary_idea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='marker_drafts', to='tripapp.itineraryidea')),
            ],
            options={
                'ordering': ['sequence'],
            },
        ),
    ]
