# Generated by Django 4.2.30 on 2026-05-06 18:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tripapp', '0050_mapmarkerdraft'),
    ]

    operations = [
        migrations.AlterField(
            model_name='overnightlocation',
            name='day',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='overnightlocations', to='tripapp.itineraryideaday'),
        ),
    ]
