# Generated by Django 4.2.30 on 2026-05-10 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tripapp', '0051_alter_overnightlocation_day'),
    ]

    operations = [
        migrations.AddField(
            model_name='tripper',
            name='home_location',
            field=models.CharField(blank=True, help_text='Name/address of home location. Will be used as starting point for brainstorm map', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='tripper',
            name='home_location_lat',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tripper',
            name='home_location_lon',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
