# Generated by Django 4.2.30 on 2026-05-22 19:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tripapp', '0052_tripper_home_location_tripper_home_location_lat_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='checklist',
            name='suggestion_job',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tripapp.ollamajob'),
        ),
    ]
