# Generated by Django 4.2.30 on 2026-05-24 14:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tripapp', '0053_checklist_suggestion_job'),
    ]

    operations = [
        migrations.CreateModel(
            name='DayVibe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vibe', models.CharField(max_length=10)),
                ('note', models.CharField(blank=True, max_length=140)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('dayprogram', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vibes', to='tripapp.dayprogram')),
                ('tripper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vibes', to='tripapp.tripper')),
            ],
            options={
                'unique_together': {('dayprogram', 'tripper')},
            },
        ),
    ]
