# Generated by Django 4.2.30 on 2026-05-25 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tripapp', '0054_dayvibe'),
    ]

    operations = [
        migrations.AddField(
            model_name='tripexpense',
            name='split_among',
            field=models.ManyToManyField(blank=True, help_text='Select which trippers should share this expense. If empty, all trippers are assumed.', related_name='expenses_to_split', to='tripapp.tripper'),
        ),
    ]
