# Generated by Django 4.2.30 on 2026-06-13 15:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tripapp', '0058_poll_polloption_pollvote'),
    ]

    operations = [
        migrations.CreateModel(
            name='ThingToDo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_description', models.CharField(max_length=200)),
                ('more_info', models.TextField(blank=True)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('overnight_location', models.CharField(blank=True, max_length=255, null=True)),
                ('assigned_date', models.DateField(blank=True, null=True)),
                ('point', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='thing_to_do', to='tripapp.point')),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='things_to_do', to='tripapp.trip')),
            ],
        ),
    ]
