# Generated by Django 4.2.30 on 2026-08-16 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tripapp', '0060_tripper_preferred_itinerary_view_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduleditem',
            name='description',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='preferred_itinerary_view',
            field=models.CharField(choices=[('day', 'Day and Destination'), ('daynight', 'Day and Night location'), ('dayvibe', 'Day Vibe')], default='osm', help_text='Preferred itinerary view', max_length=20),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='preferred_map_view',
            field=models.CharField(choices=[('osm', 'OpenStreetMap (Standard)'), ('satellite', 'Satellite (ESRI)')], default='osm', help_text='Preferred map view: standard or satellite', max_length=20),
        ),
    ]
