# Generated by Django 4.2.30 on 2026-08-17 21:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tripapp', '0061_scheduleditem_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tripper',
            name='preferred_itinerary_view',
        ),
        migrations.RemoveField(
            model_name='tripper',
            name='preferred_map_view',
        ),
        migrations.AddField(
            model_name='location',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='location',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='point',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='point',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='route',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='route',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='route',
            name='uploaded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tripapp.tripper'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='preferred_itinerary_view',
            field=models.CharField(choices=[('day', 'Day and Destination'), ('daynight', 'Day and Night location'), ('dayvibe', 'Day Vibe'), ('focus', 'Focus (Today & Upcoming)')], default='osm', help_text='Preferred itinerary view', max_length=20),
        ),
    ]
