# Generated by Django 4.2.30 on 2026-08-22 19:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tripapp', '0063_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='logentrylike',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='logentry_likes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='logentrylike',
            name='tripper',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='logentry_likes', to='tripapp.tripper'),
        ),
    ]
