# Generated by Django 4.2.30 on 2026-08-22 19:50


from django.db import migrations

def populate_user_from_tripper(apps, schema_editor):
    LogEntryLike = apps.get_model('tripapp', 'LogEntryLike')
    for like in LogEntryLike.objects.select_related('tripper', 'tripper__user'):
        if like.tripper and like.tripper.user:
            like.user = like.tripper.user
            like.save(update_fields=['user'])
        else:
            like.delete()

def reverse_noop(apps, schema_editor):
    pass  # niet terug te draaien, tripper-koppeling blijft intact dus geen echte reverse nodig

class Migration(migrations.Migration):

    dependencies = [
        ('tripapp', '0064_logentrylike_user_alter_logentrylike_tripper'),
    ]

    operations = [
        migrations.RunPython(populate_user_from_tripper, reverse_noop),
    ]