# Generated by Django 4.2.30 on 2026-08-24 15:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tripapp', '0065_populate_logentrylike_user'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='logentrylike',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='logentrylike',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logentry_likes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='logentrylike',
            unique_together={('logentry', 'user', 'emoji')},
        ),
        migrations.RemoveField(
            model_name='logentrylike',
            name='tripper',
        ),
    ]
