# Generated by Django 4.2.30 on 2026-08-24 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tripapp', '0066_alter_logentrylike_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='point',
            name='address',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
