# Generated by Django 4.2.30 on 2026-08-28 07:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tripapp', '0067_point_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='tribe',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_tribes', to=settings.AUTH_USER_MODEL),
        ),
    ]
