# Generated by Django 4.2.30 on 2026-09-19 16:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tripapp', '0068_tribe_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='timezone_name',
            field=models.CharField(blank=True, help_text='IANA-timezone of destination, example: Asia/Tokyo.', max_length=64),
        ),
        migrations.CreateModel(
            name='CalendarFeedToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(editable=False, max_length=64, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='calendar_feed', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
