# Generated by Django 4.2.30 on 2026-09-20 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tripapp', '0069_trip_timezone_name_calendarfeedtoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduleditem',
            name='end_timezone',
            field=models.CharField(blank=True, help_text='Timezone of the end time, e.g. Asia/Tokyo. Empty = same as start.', max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='scheduleditem',
            name='start_timezone',
            field=models.CharField(blank=True, help_text='Timezone of the start time, e.g. Europe/Amsterdam. Empty = trip timezone.', max_length=64, null=True),
        ),
    ]
